apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "terraform-hostpath"
  labels:
    app: terraform-test
spec:
  volumeMode: Filesystem
  storageClassName: hostpath-provisioner
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi